### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by L4wlight** [ScaredKurufinve/Way-of-the-shield#1]
Every attempt to turn off the flanking and / or softcover rules failed so far for me. Same for the changes to Shieldwall and Shield spell.   Tried it both with UMM and ModMenu menu. It let's me save the changes with "apply", but after a restart they are back on.

**Comment by ScaredKurufinve** [comment]
Thank you for feedback. I will look into it.

**Comment by ScaredKurufinve** [comment]
I seemingly fixed the issue. The flanking rule was intended to be a per-save setting, but it required some code to be run at the game launch.  All settings except for the Rapier one are now not per-save (should probably clarify this at the description when I release a proper version 1.0 after the beta branch goes live).
