### ISSUE TITLE
Shielded Mage (Shield Mastery)?

### ISSUE THREAD

**Issue by CaptOcto** [ScaredKurufinve/Way-of-the-shield#10]
Hi, does your mod have the Shielded Mage feat implemented by chance?

**Comment by CaptOcto** [comment]
Tried downloading your mod to have a look but mod menu says it has errors.

**Comment by ScaredKurufinve** [comment]
No, it does not have Shielded Mage, but that is a good suggestion to add.

ModMenu or ModFinder?

**Comment by ScaredKurufinve** [comment]
Added in version 1.0.3

**Comment by CaptOcto** [comment]
Cool! I will try to download the mod again. I was using ModFinder for
installation and the window in game said there was an error with the mod.

**Comment by ScaredKurufinve** [comment]
this is strange, because other people are using ModFinder to install it and everything is fine. If it keeps saying there are errors, can you please send me your GameLogFull and UMM log?

**Comment by CaptOcto** [comment]
This will be available as a Loremaster Secret: Combat Feat right?

**Comment by ScaredKurufinve** [comment]
M-m-m, no. The srd mentions it only as a Shield Mastery feat, not as a Combat Feat. It will be available only in the standart feat selection and in the Shield Mastery selection for fighters if you are using TableTopTweaks-base. I don't know if TTT adds Shield Mastery to Loremasters

**Comment by CaptOcto** [comment]
When I look on the Shield Mastery Feats page (
https://www.d20pfsrd.com/feats/shield-mastery-feats/) it says that "Shield
mastery feats count as combat feats
<https://www.d20pfsrd.com/feats/combat-feats> for all purposes, including
which classes can select them as bonus feat"?

The conflict between WotR Loremaster and PF Loremaster on the other hand...
(TTT at least changes requirements to match PF but doesn't nerf the secrets
to TTT rules level).

**Comment by ScaredKurufinve** [comment]
Hm, that was indeed a misunderstanding on my side. Thank you for clarifying it. I'll add it to the Combat Feat selection directly in the next update. As for now, I did check and TTT does brings the whole Shield Mastery group to Combat Feats, so you should be able to get the feat as Lore Master anyways.

**Comment by CaptOcto** [comment]
Perfect thanks 😊

**Comment by CaptOcto** [comment]
How does your mod interact with TTT (Flanking)? Maybe they can't be installed together?

Is it possible to choose which parts of your mod I want to have active?

**Comment by ScaredKurufinve** [comment]
I never tried it in conjunction with TTT-flanking (as I created mine before Vek's), but it probably won't work out. 

Yes, you may choose what parts of my mod to enable / disable in mod settings.

**Comment by Dza101** [comment]
I've been using it with TTT-flanking, with the flanking component on this mod disabled. The only thing I've noticed is that there are now two 'Improved Outflank' feats.
