### ISSUE TITLE
Unhindering Shield doesn't work for Sohei monk archetype

### ISSUE THREAD

**Issue by poridore** [ScaredKurufinve/Way-of-the-shield#12]
Sohei loose it's flurry of blows and ac bonus after equipping a buckler. Holding a weapon (with weapon training) or none have no effect.
Unhindering Shield work for standard monk.

**Comment by ScaredKurufinve** [comment]
thanks for information. I'll try to fix this on weekends

**Comment by ScaredKurufinve** [comment]
Should work now on version 1.0.3

**Comment by poridore** [comment]
It work now. Thank you for the fix.
