### ISSUE TITLE
Friendly Fire Maneuvers Prerequisite

### ISSUE THREAD

**Issue by nixgnot** [ScaredKurufinve/Way-of-the-shield#13]
cant learn it while meet Prerequisites
![QQ截图20230325182038](https://user-images.githubusercontent.com/20860979/227711403-1f938569-33df-4129-9ff6-73ab9cb505f6.png)
![QQ截图20230325182054](https://user-images.githubusercontent.com/20860979/227711406-11a89472-c82b-45ab-8909-43f662f20228.png)

btw, i see a BUFF blueprint of Friendly Fire Maneuvers . but i CANT get that BUFF even after i learn that feat (unlock the Prerequisite by toybox) -- so that feat looks like not work at all.

**Comment by ScaredKurufinve** [comment]
Should work now on version 1.0.3
