### ISSUE TITLE
Lost buckler proficiency

### ISSUE THREAD

**Issue by Dza101** [ScaredKurufinve/Way-of-the-shield#14]
Hi there, after loading the mod (latest version) I had unchecked 'Remove buckler proficiency from several classes' because I didn't want homebrew changes.

However, when loading my save game, my Warpriest shieldbearer had lost his buckler proficiency.

**Comment by Dza101** [comment]
Also, it would be nice if 'Shielded defence' was toggleable on the Mod Menu.

Thanks!

**Comment by ScaredKurufinve** [comment]
Hm, this is very strange. Thank you very much for the report.

**Comment by Dza101** [comment]
And no longer have buckler parry on all my characters.

**Comment by Dza101** [comment]
I guess the only issue would be the choice to have  Shielded Defence optional on the mod menu?

**Comment by Dza101** [comment]
Thanks!

**Comment by ScaredKurufinve** [comment]
Good to hear it resolved on its own. Even though I still don't understand why this would happen in the first place.

Somehow I was sure I had a setting for all 3 new shield abilities, but looks like I don't :D I'll add it next time I update. And if the mod stops causing people random problems to people again and again, maybe I'll finally be able to work on the ModMenu extension which will allow me to group settings better.

If there's no more problems with the proficiency, feel free to close the issue :)

**Comment by Dza101** [comment]
great
