### ISSUE TITLE
Suggestion: Low Profile

### ISSUE THREAD

**Issue by Dza101** [ScaredKurufinve/Way-of-the-shield#15]
So the new cover rules make ranged combat a lot more challenging (no complaints there!)

I was wondering if it would be possible to implement the feat 'Low Profile'?

https://www.d20pfsrd.com/feats/combat-feats/low-profile-combat/

I think it would be quite useful within the context of your mod!

Thanks! Great mod

**Comment by ScaredKurufinve** [comment]
Great suggestion! Thanks!
