### ISSUE TITLE
-8 Soft cover penalty?

### ISSUE THREAD

**Issue by Dza101** [ScaredKurufinve/Way-of-the-shield#16]
Hi there,

I'm sometimes getting a -8 soft cover penalty with my halfling archer. I was under the impression that soft cover is max -4 penalty.

**Comment by ScaredKurufinve** [comment]
In my rulings the soft cover bonus depends on the difference between the target and the creature that provides the cover. I did consider making a setting for this, but kinda did not get to do it yet.

**Comment by Dza101** [comment]
Ok, for reference, the target was huge size (Star Rattle), the obstacle was medium size (spirit paladin), and the attacker was small size (Halfling).

Since the obstacle was so much smaller than the target (two sizes smaller) shouldn't the penalty be less?

**Comment by ScaredKurufinve** [comment]
Thank you very much! There was indeed a bug - I was checking the attacker's size instead of the target. Will be fixed in the next update.
![1](https://user-images.githubusercontent.com/126824833/228563663-4a46c2bc-a926-40a2-822f-fdfde242eaca.jpg)
