### ISSUE TITLE
Despite backstab mechanic disabled, target loses Dex bonus

### ISSUE THREAD

**Issue by Dza101** [ScaredKurufinve/Way-of-the-shield#17]
I have the backstab mechanic disabled, but target still loses Dex bonus when getting attacked from behind. They show up in the combat log as (flatfooted, backstab) whereas they don't when they're being attacked from the front by another attacked and still get their Dex bonus.

**Comment by ScaredKurufinve** [comment]
I see the issue and will fix it as soon as...

**Comment by Dza101** [comment]
Hi! I just checked, and the Concealment was enabled, but not the concealment bonus. I disabled both now. Sorry about that. I'm guessing it should work normally now.

**Comment by Dza101** [comment]
Guess I should close
