### ISSUE TITLE
Bastion of Good is not working correctly in my game

### ISSUE THREAD

**Issue by Bigeam** [ScaredKurufinve/Way-of-the-shield#20]
Hello, I am enjoying sacred shield archetypes, but I have some problems with the ability bastion of good. When the target hits my teammate, the damage isn't halved. And aroden's wrath can't change ac bonus to sacred like it do with smite evil but keeps deflection .

**Comment by ScaredKurufinve** [comment]
Thank you for bug report. I'll see into.

**Comment by Bigeam** [comment]
Thank you for fixing

**Comment by ScaredKurufinve** [comment]
Can you please confirm to me that Bastion of Good works correctly on the current game version? It does for me, but another person on Discord shows shows screenshots of it not working :(

**Comment by Bigeam** [comment]
> Can you please confirm to me that Bastion of Good works correctly on the current game version? It does for me, but another person on Discord shows shows screenshots of it not working :(

the ac part work but  the damage reduction part still not work for me

**Comment by ScaredKurufinve** [comment]
Hm, good to know.
