### ISSUE TITLE
error was found in the gamelog file

### ISSUE THREAD

**Issue by tafeilgh** [ScaredKurufinve/Way-of-the-shield#25]
[139.5280 - Way Of The Shield]: Failed to find and index when transpiling
Way_of_the_shield.Utilities.IndexFinder(System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction],HarmonyLib.CodeInstruction[],System.Boolean) (at :0)
Way_of_the_shield.NewFeatsAndAbilities.UnhinderingShield.MonkNoArmorAndMonkWeaponFeatureUnlock_CheckEligibility_Transpiler(System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction]) (at :0)
System.Reflection.MonoMethod.InternalInvoke(System.Object,System.Object[],System.Exception&) (at :0)
System.Reflection.MonoMethod.Invoke(System.Object,System.Reflection.BindingFlags,System.Reflection.Binder,System.Object[],System.Globalization.CultureInfo) (at :0)
System.Reflection.MethodBase.Invoke(System.Object,System.Object[]) (at :0)
HarmonyLib.CodeTranspiler+<>c__DisplayClass12_0.<GetResult>b__0(System.Reflection.MethodInfo) (at :0)
System.Collections.Generic.List`1[[System.Reflection.MethodInfo, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1[System.Reflection.MethodInfo]) (at :0)
HarmonyLib.CodeTranspiler.GetResult(System.Reflection.Emit.ILGenerator,System.Reflection.MethodBase) (at :0)
HarmonyLib.MethodBodyReader.FinalizeILCodes(HarmonyLib.Emitter,System.Collections.Generic.List`1[System.Reflection.MethodInfo],System.Collections.Generic.List`1[System.Reflection.Emit.Label],System.Boolean&) (at :0)
HarmonyLib.MethodCopier.Finalize(HarmonyLib.Emitter,System.Collections.Generic.List`1[System.Reflection.Emit.Label],System.Boolean&) (at :0)
HarmonyLib.MethodPatcher.CreateReplacement(System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]&) (at :0)
HarmonyLib.PatchFunctions.UpdateWrapper(System.Reflection.MethodBase,HarmonyLib.PatchInfo) (at :0)
HarmonyLib.PatchClassProcessor.ProcessPatchJob(HarmonyLib.PatchJobs`1+Job[System.Reflection.MethodInfo]) (at :0)
HarmonyLib.PatchClassProcessor.PatchWithAttributes(System.Reflection.MethodBase&) (at :0)
HarmonyLib.PatchClassProcessor.Patch() (at :0)
Shared.Main.Patch(System.Type) (at :0)
DarkCodex.Monk.PatchSoheiRapidShot() (at :0)
Shared.Main.LoadSafe(System.Action) (at :0)
Shared.Main.OnBlueprintsLoaded() (at :0)
Shared.Main+Patches.Postfix2() (at :0)
Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadAllJson_Patch7(Kingmaker.Blueprints.JsonSystem.StartGameLoader,System.String) (at :0)
Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)
UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)

**Comment by ScaredKurufinve** [comment]
Thank you for the report, but this is not a real error, this is me being very lazy with coding :) This specific patch has to be applied several times, so I decided to keep applying it until it throws an error about being unable to do that anymore. I'll probably change this to a more sane way, because a lot of people seem to be annoyed by that.

Accidentally, this very patch has an (already-fixed-but-not-yet-released) incompatibility with Dark Codex fix for Sohei Rapid Shot, but it throws no errors on my side 🤷‍♂️
