### ISSUE TITLE
have a look at concealment

### ISSUE THREAD

**Issue by KTVSUN** [ScaredKurufinve/Way-of-the-shield#29]

**Comment by KTVSUN** [comment]
[GameLog.txt](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11713348/GameLog.txt)
[Player.log](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11713349/Player.log)
<img width="827" alt="image" src="https://github.com/ScaredKurufinve/Way-of-the-shield/assets/132005138/4462b211-07a9-4751-a919-af9c5340d2b6">

**Comment by ScaredKurufinve** [comment]
Assuming it is not indeed caused by Aivu as you mentioned on Discord, I'd need PlayerLogFull which contains all of my debug info (when you are using the dll from Debug folder)

**Comment by KTVSUN** [comment]
ok i ll reinstall dll
can i keep it on all the time

**Comment by KTVSUN** [comment]
it s definitely because of target being blind, i reloiaded
