### ISSUE TITLE
0.92 cause a save error at the game start

### ISSUE THREAD

**Issue by nixgnot** [ScaredKurufinve/Way-of-the-shield#5]
while i using 0.92, it always cause a save error after the coversation at the beginning.
![1](https://user-images.githubusercontent.com/20860979/223144724-f604481f-c138-4aab-9e4f-38954aad7e67.png)
then it will always cause the game crash after i fall down, then break the autosave.
![2](https://user-images.githubusercontent.com/20860979/223145690-8e669f85-2562-40b5-9178-85df8f18552f.png)

unfortunately i cant sure is there a confilct..because i have many mods actived.

Earlier version (including that file for test which you sent me on discord :P) do not cause this

**Comment by ScaredKurufinve** [comment]
Fixed. Woe me, always forget to use my own tools to not breaking anything.
