### ISSUE TITLE
Shielded Defense does not work

### ISSUE THREAD

**Issue by Sakurasrb** [ScaredKurufinve/Way-of-the-shield#6]
I'm sure I have turned on it and I do see Two-Weapon Fighting penalties, but there's no additional AC bonus on the shield.

**Comment by ScaredKurufinve** [comment]
Can I assume that you are using the Shielded Defense without using Fighting Defensively. Looks like I did not include this part into the ability description. It should not give the penalty when Fighting Defensively is enabled. Note taken.

**Comment by ScaredKurufinve** [comment]
Oh, I see. It does not get the base value. Thank you for pointing it out.

**Comment by ScaredKurufinve** [comment]
Tell me please, if version 1.0.2.0 fixed it

**Comment by Sakurasrb** [comment]
The new version seems to have some terrible bugs, and now when I try to start my game, whether by loading a save or starting a new game, the mod menu just disappears and mods based on it now do not work anymore. Also, I can not attack enemies in the battle, and I think it might just result from the issue above.

**Comment by Sakurasrb** [comment]
> > The new version seems to have some terrible bugs, and now when I try to start my game, whether by loading a save or starting a new game, the mod menu just disappears and mods based on it now do not work anymore. Also, in the new version I can not attack enemies in the combat, and I think it might just result from the issue above.
> 
> There seems to be some very strange interaction between my mod and TTT. I left a "hotfix" on Discord in the mod-user channel - affected people say it helps, but I need some more time to make it into a release, because it does the opposite to me.

The hotfix does work, and now the Shielded Defense also seems to work quite well. Thx for your work! But still, this time BucklerParry just can not be turned on, is that a bug or something else?

**Comment by ScaredKurufinve** [comment]
Most likely a bug. The only restriction on Buckler Parry is to have buckler or light shield equipped (not even a proficiency). But on my test saves everything is fine. Can you please send your GameLogFull after you try to activate it?

**Comment by Sakurasrb** [comment]
> Most likely a bug. The only restriction on Buckler Parry is to have buckler or light shield equipped (not even a proficiency). But on my test saves everything is fine. Can you please send your GameLogFull after you try to activate it?

I will send it later after work. And one little guess for the bug, I downloaded the 1.2.0 ver from the main page, because the info txt of latest mod downloaded from release page was still marked as 1.1.0. I wonder would it be the true reason for the bug?
